### ISSUE TITLE
What did you think about the process of writing a command?

### ISSUE THREAD

**Issue by danielbachhuber** [binarygary/db-checkpoint#6]
What went well, and what could be improved? Any documentation changes you'd suggest?

**Comment by binarygary** [comment]
I started this out as a plugin with WP_CLI functionality.
But, for this use case a plugin seemed pretty heavy handed. 

I am currently having an issue with the package if I install it from within wp-cli vs as a plugin as developed.  

specifically relying on wp functionality to be available: https://github.com/binarygary/db-checkpoint/issues/8

Anyway, I do have some thoughts on documentation notes and when I can sit down and think through them I'll let ya know.

Thanks for shepherding WP-CLI...totally indispensable tool!

**Comment by danielbachhuber** [comment]
> Anyway, I do have some thoughts on documentation notes and when I can sit down and think through them I'll let ya know.

Sounds good :)

> Thanks for shepherding WP-CLI...totally indispensable tool!

Glad to hear!

**Comment by binarygary** [comment]
@danielbachhuber One area that confused me...and that I'm still not totally clear on is registration arguments.  Initially I was annotating with a docblock but opted to use the 3rd param in add_command. 
I'd like to see an expanded example of that 3rd $args param that matches the full docblock example. 
'examples' would be the key but I don't know what display decision options WP CLI will make.

My other comment isn't nearly as specific and it may be my experience/expectation coloring my understanding.  When I think WP development I think plugins...and in fact I started this project as a plugin, submitted it to the .org repo and then realized that the package manager existed.  So, maybe a short blurb about how a package is different than a plugin.  

http://wp-cli.org/docs/commands-cookbook/ is pretty thorough and also long. The headings are good, but it may benefit from being multiple pages...or tabbed...or...I dunno (front end thoughts?).  I missed reading some stuff because it was a lot to digest. However, that being said...it is thorough and that's great. 

I've not worked on this side of composer and found it really easy based on the cookbook page info.  Thanks for that.

**Comment by danielbachhuber** [comment]
> My other comment isn't nearly as specific and it may be my experience/expectation coloring my understanding. When I think WP development I think plugins...and in fact I started this project as a plugin, submitted it to the .org repo and then realized that the package manager existed. So, maybe a short blurb about how a package is different than a plugin.

How would you phrase this, and where would you put it?

**Comment by binarygary** [comment]
I think I'd put it somewhere near the top.
(Though in the future I'll use the package generator.)

Something like...

> Packages are to WP-CLI as plugins are to WordPress there are distinct differences in the approach you should take to creating a WP-CLI package.
> While WP-CLI is an ever-growing alternative to /wp-admin it is important to note that you must first write your package to work with the WP-CLI internal API before considering how you work with WordPress APIs.

**Comment by danielbachhuber** [comment]
> I think I'd put it somewhere near the top.

@binarygary Want to submit a PR for it? The page is editable through an "Edit" link at the top
